// examples/vue/AnimatedMap.vue
<!--
  MapLibre Animated Shaders - Vue 3 Example

  This example demonstrates how to integrate maplibre-animated-shaders
  with Vue 3 using the Composition API.

  Installation:
    npm install maplibre-gl maplibre-animated-shaders vue
-->

<template>
  <div class="animated-map-container">
    <div ref="mapContainer" class="map"></div>

    <div class="controls">
      <h3>Shader Controls</h3>

      <div class="control-group">
        <label for="shader-select">Effect</label>
        <select id="shader-select" v-model="currentShader" @change="onShaderChange">
          <option v-for="shader in availableShaders" :key="shader" :value="shader">
            {{ getShaderDisplayName(shader) }}
          </option>
        </select>
      </div>

      <div class="control-group">
        <label for="speed">Animation Speed</label>
        <input
          id="speed"
          type="range"
          v-model.number="config.speed"
          min="0.1"
          max="3"
          step="0.1"
          @input="updateShader"
        />
        <span class="value">{{ config.speed.toFixed(1) }}x</span>
      </div>

      <div class="control-group">
        <label for="intensity">Intensity</label>
        <input
          id="intensity"
          type="range"
          v-model.number="config.intensity"
          min="0.1"
          max="2"
          step="0.1"
          @input="updateShader"
        />
        <span class="value">{{ config.intensity.toFixed(1) }}</span>
      </div>

      <div class="control-group">
        <label>
          <input type="checkbox" v-model="isPlaying" @change="togglePlayback" />
          Animation Playing
        </label>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, reactive, watch } from 'vue';
import maplibregl, { Map as MapLibreMap } from 'maplibre-gl';
import {
  ShaderManager,
  globalRegistry,
  examplePlugin,
  PluginManager,
} from 'maplibre-animated-shaders';

import 'maplibre-gl/dist/maplibre-gl.css';

// Register built-in shaders
const pluginManager = new PluginManager(globalRegistry);
pluginManager.use(examplePlugin);

// Props
interface Props {
  center?: [number, number];
  zoom?: number;
  styleUrl?: string;
  initialShader?: string;
}

const props = withDefaults(defineProps<Props>(), {
  center: () => [-74.5, 40],
  zoom: 9,
  styleUrl: 'https://demotiles.maplibre.org/style.json',
  initialShader: 'plasma',
});

// Emits
const emit = defineEmits<{
  (e: 'map-ready', map: MapLibreMap): void;
  (e: 'shader-change', shader: string): void;
}>();

// Refs
const mapContainer = ref<HTMLDivElement | null>(null);
const map = ref<MapLibreMap | null>(null);
const shaderManager = ref<ShaderManager | null>(null);
const currentShader = ref(props.initialShader);
const currentLayerId = ref<string | null>(null);
const isPlaying = ref(true);

// Reactive config
const config = reactive({
  speed: 1.0,
  intensity: 1.0,
  opacity: 0.7,
});

// Computed
const availableShaders = globalRegistry.list();

/**
 * Get display name for a shader
 */
function getShaderDisplayName(shaderName: string): string {
  const shader = globalRegistry.get(shaderName);
  return shader?.displayName || shaderName;
}

/**
 * Apply shader effect to the map
 */
function applyShader(shaderName: string): void {
  if (!map.value) return;

  const shader = globalRegistry.get(shaderName);
  if (!shader) {
    console.error(`Shader "${shaderName}" not found`);
    return;
  }

  // Initialize shader manager if needed
  if (!shaderManager.value) {
    shaderManager.value = new ShaderManager(globalRegistry);
  }

  // Remove existing layer
  if (currentLayerId.value && map.value.getLayer(currentLayerId.value)) {
    map.value.removeLayer(currentLayerId.value);
  }

  // Ensure source exists
  if (!map.value.getSource('shader-source')) {
    map.value.addSource('shader-source', {
      type: 'geojson',
      data: {
        type: 'FeatureCollection',
        features: [
          {
            type: 'Feature',
            geometry: {
              type: 'Polygon',
              coordinates: [
                [
                  [-180, -85],
                  [180, -85],
                  [180, 85],
                  [-180, 85],
                  [-180, -85],
                ],
              ],
            },
            properties: {},
          },
        ],
      },
    });
  }

  // Create new layer
  const layerId = `shader-${shaderName}-${Date.now()}`;
  const mergedConfig = { ...shader.defaultConfig, ...config };

  map.value.addLayer({
    id: layerId,
    type: 'fill',
    source: 'shader-source',
    paint: {
      'fill-color': (mergedConfig.color as string) || '#3388ff',
      'fill-opacity': config.opacity,
    },
  });

  currentLayerId.value = layerId;
  shaderManager.value.register(shaderName, shader);

  console.log(`Applied shader: ${shaderName}`, mergedConfig);
}

/**
 * Handle shader selection change
 */
function onShaderChange(): void {
  applyShader(currentShader.value);
  emit('shader-change', currentShader.value);
}

/**
 * Update shader with current config
 */
function updateShader(): void {
  applyShader(currentShader.value);
}

/**
 * Toggle animation playback
 */
function togglePlayback(): void {
  // In a real implementation, you would call the shader manager's
  // play/pause methods here
  console.log(`Animation ${isPlaying.value ? 'playing' : 'paused'}`);
}

// Lifecycle hooks
onMounted(() => {
  if (!mapContainer.value) return;

  map.value = new maplibregl.Map({
    container: mapContainer.value,
    style: props.styleUrl,
    center: props.center,
    zoom: props.zoom,
  });

  map.value.on('load', () => {
    emit('map-ready', map.value!);
    applyShader(currentShader.value);
  });
});

onUnmounted(() => {
  map.value?.remove();
  map.value = null;
  shaderManager.value = null;
});

// Watch for prop changes
watch(() => props.initialShader, (newShader) => {
  currentShader.value = newShader;
  if (map.value) {
    applyShader(newShader);
  }
});

// Expose methods for parent components
defineExpose({
  map,
  applyShader,
  getAvailableShaders: () => availableShaders,
});
</script>

<style scoped>
.animated-map-container {
  position: relative;
  width: 100%;
  height: 100%;
}

.map {
  width: 100%;
  height: 100%;
}

.controls {
  position: absolute;
  top: 10px;
  left: 10px;
  background: white;
  padding: 15px;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
  z-index: 1000;
  min-width: 200px;
}

.controls h3 {
  margin: 0 0 15px 0;
  font-size: 14px;
  color: #333;
}

.control-group {
  margin-bottom: 12px;
}

.control-group label {
  display: block;
  margin-bottom: 5px;
  font-size: 12px;
  color: #666;
}

.control-group select,
.control-group input[type='range'] {
  width: 100%;
}

.control-group select {
  padding: 5px;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.control-group input[type='checkbox'] {
  width: auto;
  margin-right: 5px;
}

.value {
  display: block;
  text-align: right;
  font-size: 11px;
  color: #999;
  margin-top: 2px;
}
</style>

// examples/react/AnimatedMap.tsx
/**
 * MapLibre Animated Shaders - React Example
 *
 * This example demonstrates how to integrate maplibre-animated-shaders
 * with React using hooks for lifecycle management.
 *
 * Installation:
 *   npm install maplibre-gl maplibre-animated-shaders react react-dom
 */

import React, { useEffect, useRef, useState, useCallback } from 'react';
import maplibregl, { Map as MapLibreMap } from 'maplibre-gl';
import {
  ShaderManager,
  globalRegistry,
  examplePlugin,
  PluginManager,
} from 'maplibre-animated-shaders';
import type { ShaderDefinition } from 'maplibre-animated-shaders';

import 'maplibre-gl/dist/maplibre-gl.css';

// Register built-in shaders once at module level
const pluginManager = new PluginManager(globalRegistry);
pluginManager.use(examplePlugin);

/**
 * Props for the AnimatedMap component
 */
interface AnimatedMapProps {
  /** Initial map center [lng, lat] */
  center?: [number, number];
  /** Initial zoom level */
  zoom?: number;
  /** Map style URL */
  styleUrl?: string;
  /** Initial shader to apply */
  initialShader?: string;
  /** Shader configuration */
  shaderConfig?: Record<string, unknown>;
  /** Callback when map is ready */
  onMapReady?: (map: MapLibreMap) => void;
  /** Callback when shader changes */
  onShaderChange?: (shaderName: string) => void;
}

/**
 * Hook for managing shader effects on a MapLibre map
 */
function useShaderEffect(
  map: MapLibreMap | null,
  shaderName: string | null,
  config: Record<string, unknown> = {}
) {
  const shaderManagerRef = useRef<ShaderManager | null>(null);
  const currentLayerRef = useRef<string | null>(null);

  useEffect(() => {
    if (!map || !shaderName) return;

    const shader = globalRegistry.get(shaderName);
    if (!shader) {
      console.error(`Shader "${shaderName}" not found`);
      return;
    }

    // Initialize shader manager
    if (!shaderManagerRef.current) {
      shaderManagerRef.current = new ShaderManager(globalRegistry);
    }

    const layerId = `shader-${shaderName}-${Date.now()}`;

    // Cleanup previous layer
    if (currentLayerRef.current) {
      if (map.getLayer(currentLayerRef.current)) {
        map.removeLayer(currentLayerRef.current);
      }
      if (map.getSource('shader-source')) {
        map.removeSource('shader-source');
      }
    }

    // Add shader source if not exists
    if (!map.getSource('shader-source')) {
      map.addSource('shader-source', {
        type: 'geojson',
        data: {
          type: 'FeatureCollection',
          features: [
            {
              type: 'Feature',
              geometry: {
                type: 'Polygon',
                coordinates: [
                  [
                    [-180, -85],
                    [180, -85],
                    [180, 85],
                    [-180, 85],
                    [-180, -85],
                  ],
                ],
              },
              properties: {},
            },
          ],
        },
      });
    }

    // Merge config with defaults
    const mergedConfig = { ...shader.defaultConfig, ...config };

    // Add the shader layer
    map.addLayer({
      id: layerId,
      type: 'fill',
      source: 'shader-source',
      paint: {
        'fill-color': (mergedConfig.color as string) || '#3388ff',
        'fill-opacity': (mergedConfig.opacity as number) || 0.7,
      },
    });

    currentLayerRef.current = layerId;
    shaderManagerRef.current.register(shaderName, shader);

    // Cleanup on unmount or shader change
    return () => {
      if (map.getLayer(layerId)) {
        map.removeLayer(layerId);
      }
    };
  }, [map, shaderName, JSON.stringify(config)]);

  return shaderManagerRef.current;
}

/**
 * AnimatedMap - A React component for MapLibre maps with animated shader effects
 *
 * @example
 * ```tsx
 * <AnimatedMap
 *   center={[-74.5, 40]}
 *   zoom={9}
 *   initialShader="plasma"
 *   shaderConfig={{ speed: 1.5, intensity: 1.2 }}
 * />
 * ```
 */
export function AnimatedMap({
  center = [-74.5, 40],
  zoom = 9,
  styleUrl = 'https://demotiles.maplibre.org/style.json',
  initialShader = 'plasma',
  shaderConfig = {},
  onMapReady,
  onShaderChange,
}: AnimatedMapProps) {
  const mapContainerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<MapLibreMap | null>(null);
  const [mapLoaded, setMapLoaded] = useState(false);
  const [currentShader, setCurrentShader] = useState(initialShader);

  // Get available shaders
  const availableShaders = globalRegistry.list();

  // Initialize map
  useEffect(() => {
    if (!mapContainerRef.current) return;

    const map = new maplibregl.Map({
      container: mapContainerRef.current,
      style: styleUrl,
      center,
      zoom,
    });

    map.on('load', () => {
      mapRef.current = map;
      setMapLoaded(true);
      onMapReady?.(map);
    });

    return () => {
      map.remove();
      mapRef.current = null;
      setMapLoaded(false);
    };
  }, [styleUrl]);

  // Apply shader effect
  useShaderEffect(mapLoaded ? mapRef.current : null, currentShader, shaderConfig);

  // Handle shader change
  const handleShaderChange = useCallback(
    (e: React.ChangeEvent<HTMLSelectElement>) => {
      const newShader = e.target.value;
      setCurrentShader(newShader);
      onShaderChange?.(newShader);
    },
    [onShaderChange]
  );

  return (
    <div style={{ position: 'relative', width: '100%', height: '100%' }}>
      <div
        ref={mapContainerRef}
        style={{ width: '100%', height: '100%' }}
      />
      <div
        style={{
          position: 'absolute',
          top: 10,
          left: 10,
          background: 'white',
          padding: 15,
          borderRadius: 8,
          boxShadow: '0 2px 10px rgba(0,0,0,0.2)',
          zIndex: 1000,
        }}
      >
        <label htmlFor="shader-select" style={{ display: 'block', marginBottom: 5 }}>
          Select Effect:
        </label>
        <select
          id="shader-select"
          value={currentShader}
          onChange={handleShaderChange}
          style={{ width: '100%', padding: 5 }}
        >
          {availableShaders.map((name) => (
            <option key={name} value={name}>
              {globalRegistry.get(name)?.displayName || name}
            </option>
          ))}
        </select>
      </div>
    </div>
  );
}

/**
 * Hook for direct shader management in custom components
 *
 * @example
 * ```tsx
 * function MyMap() {
 *   const { map, applyShader, removeShader } = useAnimatedShaders();
 *
 *   useEffect(() => {
 *     if (map) {
 *       applyShader('plasma', { speed: 2 });
 *     }
 *   }, [map]);
 *
 *   return <div ref={mapRef} />;
 * }
 * ```
 */
export function useAnimatedShaders() {
  const [map, setMap] = useState<MapLibreMap | null>(null);
  const shaderManagerRef = useRef<ShaderManager | null>(null);

  const applyShader = useCallback(
    (shaderName: string, config: Record<string, unknown> = {}) => {
      if (!map) return null;

      const shader = globalRegistry.get(shaderName);
      if (!shader) {
        console.error(`Shader "${shaderName}" not found`);
        return null;
      }

      if (!shaderManagerRef.current) {
        shaderManagerRef.current = new ShaderManager(globalRegistry);
      }

      shaderManagerRef.current.register(shaderName, shader);
      return shaderManagerRef.current;
    },
    [map]
  );

  const removeShader = useCallback(
    (shaderName: string) => {
      if (shaderManagerRef.current) {
        shaderManagerRef.current.unregister(shaderName);
      }
    },
    []
  );

  const listShaders = useCallback(() => {
    return globalRegistry.list();
  }, []);

  return {
    map,
    setMap,
    applyShader,
    removeShader,
    listShaders,
    shaderManager: shaderManagerRef.current,
  };
}

export default AnimatedMap;
